import type { MemeTemplate } from "./types";

/**
 * Curated Top Indian Meme & Brainrot Templates with structured beats,
 * lip-sync markers, text overlay slots, and video model prompts.
 *
 * Ported verbatim from the retired MAYA-Templates/src/curatedTemplates.ts.
 * This is the fallback set searchTrendingReels returns whenever Monid is
 * unavailable/unauthenticated, and the default set shown before any search.
 */
export const CURATED_INDIAN_MEME_TEMPLATES: MemeTemplate[] = [
  {
    templateId: "in_brainrot_01_pata_nahi",
    title: "Pata Nahi Kya Hai (Desi Existential Brainrot)",
    category: "Indian Brainrot",
    format: "talking_head_rant",
    previewVideoUrl:
      "https://assets.mixkit.co/videos/preview/mixkit-hands-holding-a-smartphone-playing-a-video-41584-large.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    durationSec: 8,
    aspectRatio: "9:16",
    viralHook: "POV: You try doing something the traditional way in 2026",
    humorMechanism: "Absurdist rant with rapid zoom-ins and sudden realisation",
    culturalContext: "High-speed Hindi/English colloquial rant popular in Indian Instagram reels community",
    metrics: { plays: 2450000, likes: 310000, comments: 14200 },
    beats: [
      {
        timestampSec: 0,
        durationSec: 2.5,
        label: "The Confusion Hook",
        visualAction: "Person stares into camera with deep distress, shaking head in disbelief",
        originalAudioCue: "Dramatic echo sound with faint Indian street ambience",
        suggestedBrandAction: "Show the agonizing manual workflow pain point",
      },
      {
        timestampSec: 2.5,
        durationSec: 3.5,
        label: "The Fast Rant",
        visualAction: "Fast-paced talking with intense hand gestures and rapid eye movement",
        originalAudioCue: "Fast paced Hindi monologue with rhythmic rising tone",
        suggestedBrandAction: "Explain the hilarious absurdity of not using the brand",
      },
      {
        timestampSec: 6.0,
        durationSec: 2.0,
        label: "The Mic Drop Punchline",
        visualAction: "Sudden freeze frame with dramatic zoom on face and smug smirk",
        originalAudioCue: "Loud Vine Boom SFX followed by Phonk bass drop",
        suggestedBrandAction: "Reveal Brand logo and 1-line solution punchline",
      },
    ],
    textSlots: [
      {
        slotId: "top_header",
        defaultText: "ME STILL DOING MANUAL WORK IN 2026:",
        placement: "top",
        fontSize: "large",
        fontStyle: "bold_impact",
        backgroundColor: "#000000CC",
        textColor: "#FFE600",
        animation: "pop_in",
      },
      {
        slotId: "bottom_punchline",
        defaultText: "Pata nahi kya chal raha hai bhai 😭",
        placement: "bottom",
        fontSize: "medium",
        fontStyle: "classic_meme",
        backgroundColor: "#DC2626EE",
        textColor: "#FFFFFF",
        animation: "typewriter",
      },
      {
        slotId: "brand_badge",
        defaultText: "Switch to Automated Growth 🚀",
        placement: "bottom_right",
        fontSize: "small",
        backgroundColor: "#0F172AEB",
        textColor: "#38BDF8",
      },
    ],
    audioPlan: {
      trackType: "bgm",
      originalSoundName: "Pata Nahi Kya Hai Original Sound (Remix)",
      suggestedTrackStyle: "High-energy Phonk with subtle Indian Tabla percussion",
      bpm: 128,
      sfxCues: [
        { timestampSec: 0.1, sfxName: "record_scratch", volumeMultiplier: 0.8 },
        { timestampSec: 2.4, sfxName: "dramatic_reverb", volumeMultiplier: 0.9 },
        { timestampSec: 6.0, sfxName: "vine_boom", volumeMultiplier: 1.0 },
      ],
    },
    lipSyncSlots: [
      {
        speakerId: "speaker_main",
        speakerDescription: "Frustrated character in oversized hoodie sitting at desk",
        startSec: 0.5,
        endSec: 5.8,
        originalDialogue:
          "Bhai mereko samajh nahi aa raha log 5 ghante kaam kaise karte hain jab 2 second me ho sakta hai!",
        emotionalExpression: "ranting",
        headMotionPrompt: "Rapid head tilts, aggressive pointing at camera, sudden wide eyes",
      },
    ],
    defaultScript:
      "Bro why are you still doing this manually when the AI tool does it in 5 seconds flat?! Pata nahi kya chal raha hai!",
    tags: ["brainrot", "rant", "hindi", "relatable", "trending_india"],
  },
  {
    templateId: "in_brainrot_02_bhai_ye_kya_hua",
    title: "Bhai Ye Kya Ho Gaya (Unexpected Shock / Reversal)",
    category: "Desi Comedy",
    format: "dramatic_reaction",
    previewVideoUrl:
      "https://assets.mixkit.co/videos/preview/mixkit-young-man-watching-a-video-on-a-smartphone-41585-large.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    durationSec: 7,
    aspectRatio: "9:16",
    viralHook: "When your competitor launches a feature vs when you launch",
    humorMechanism: "Dramatic overreaction followed by comedic silence and realization",
    culturalContext: "Hyper-dramatic soap-opera style crash zoom with comedic sound effects",
    metrics: { plays: 3890000, likes: 490000, comments: 21300 },
    beats: [
      {
        timestampSec: 0,
        durationSec: 3.0,
        label: "The False Confidence",
        visualAction: "Person smiling proudly drinking chai or typing confidently",
        originalAudioCue: "Gentle peaceful acoustic melody",
        suggestedBrandAction: "Show traditional slow results",
      },
      {
        timestampSec: 3.0,
        durationSec: 1.5,
        label: "The Shock Twist",
        visualAction: "Three rapid crash zooms onto face with jaw wide open in utter horror",
        originalAudioCue: "Indian serial dramatic thunder crash x3",
        suggestedBrandAction: "Show seeing the brand 10x output metric",
      },
      {
        timestampSec: 4.5,
        durationSec: 2.5,
        label: "The Epiphany",
        visualAction: "Character immediately grabs phone to buy/download the product",
        originalAudioCue: "Victory fanfare and joyful synth chords",
        suggestedBrandAction: "Show 1-click upgrade button and CTA",
      },
    ],
    textSlots: [
      {
        slotId: "top_header",
        defaultText: "WHEN YOU SEE THEIR REVENUE AFTER SWITCHING:",
        placement: "top",
        fontSize: "large",
        fontStyle: "bold_impact",
        backgroundColor: "#000000CC",
        textColor: "#FFFFFF",
      },
      {
        slotId: "bottom_punchline",
        defaultText: "Bhai ye kis line me aa gaye hum 💀",
        placement: "bottom",
        fontSize: "medium",
        fontStyle: "classic_meme",
        backgroundColor: "#1E1B4BEE",
        textColor: "#38BDF8",
      },
    ],
    audioPlan: {
      trackType: "bgm",
      originalSoundName: "Dramatic Dhoom Tana Remix",
      suggestedTrackStyle: "High-drama suspense building into uplifting dance drop",
      bpm: 135,
      sfxCues: [
        { timestampSec: 3.0, sfxName: "dramatic_reverb", volumeMultiplier: 1.0 },
        { timestampSec: 3.4, sfxName: "dramatic_reverb", volumeMultiplier: 1.0 },
        { timestampSec: 4.5, sfxName: "cash_register", volumeMultiplier: 0.9 },
      ],
    },
    lipSyncSlots: [
      {
        speakerId: "speaker_shocked",
        speakerDescription: "Young entrepreneur in blazer staring at laptop screen",
        startSec: 3.2,
        endSec: 6.5,
        originalDialogue: "Bhai ye magicboxai itna fast kaise chal raha hai?! Maine kal hi manually 4 ghante lagaye the!",
        emotionalExpression: "shocked",
        headMotionPrompt: "Backward jerk motion, eyes bulging, looking left and right frantically",
      },
    ],
    defaultScript:
      "Wait, they closed 50 deals in 10 minutes while I was still formatting an Excel sheet?! Bhai ye kya ho gaya?!",
    tags: ["shock", "dramatic", "hindi_meme", "reaction", "viral"],
  },
  {
    templateId: "in_brainrot_03_sigma_grindset_chai",
    title: "Sigma Chai Pe Charcha (Desi Hustle Satire)",
    category: "Sigma Satire",
    format: "sigma_grindset_satire",
    previewVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-working-on-his-laptop-308-large.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80",
    durationSec: 8,
    aspectRatio: "9:16",
    viralHook: "Rule #404: Never sleep, automate everything while sipping cutting chai",
    humorMechanism: "Ironic over-the-top alpha male hustle satire mixed with relatable desi tea stall vibe",
    culturalContext: "Indian tech hustle culture and cutting chai tapri discussions",
    metrics: { plays: 5120000, likes: 670000, comments: 32000 },
    beats: [
      {
        timestampSec: 0,
        durationSec: 3.0,
        label: "The Ultra-Focused Stare",
        visualAction: "Slow motion shot of person in sunglasses taking a sip of cutting chai at a roadside stall",
        originalAudioCue: "Slowed + Reverb Brazilian Phonk beat",
        suggestedBrandAction: "Position the user as an effortless mastermind",
      },
      {
        timestampSec: 3.0,
        durationSec: 3.0,
        label: "The Revelation",
        visualAction: "Turns smartphone screen around showing notifications flooding in",
        originalAudioCue: "Meme laser sound effect with deep sub bass",
        suggestedBrandAction: "Showcase brand metrics & live dashboard revenue",
      },
      {
        timestampSec: 6.0,
        durationSec: 2.0,
        label: "The Sigma Smile",
        visualAction: "Subtle nod, jaw clench, walking into slow-motion sunset with chai glass",
        originalAudioCue: "Gigachad theme drop with echo",
        suggestedBrandAction: "Brand logo sign-off and link in bio CTA",
      },
    ],
    textSlots: [
      {
        slotId: "top_header",
        defaultText: "WHILE THEY WERE BUSY OVERTHINKING:",
        placement: "top",
        fontSize: "large",
        fontStyle: "bold_impact",
        backgroundColor: "#000000CC",
        textColor: "#F59E0B",
      },
      {
        slotId: "bottom_punchline",
        defaultText: "WE AUTOMATED THE ENTIRE BUSINESS OVER 1 CHAI ☕🗿",
        placement: "bottom",
        fontSize: "medium",
        fontStyle: "neon_glow",
        backgroundColor: "#000000EE",
        textColor: "#FFFFFF",
      },
    ],
    audioPlan: {
      trackType: "bgm",
      originalSoundName: "Sigma Desi Phonk Slowed",
      suggestedTrackStyle: "Heavy bass phonk with atmospheric reverb",
      bpm: 120,
      sfxCues: [
        { timestampSec: 3.1, sfxName: "laser", volumeMultiplier: 0.7 },
        { timestampSec: 6.0, sfxName: "vine_boom", volumeMultiplier: 1.0 },
      ],
    },
    lipSyncSlots: [
      {
        speakerId: "speaker_sigma",
        speakerDescription: "Confident protagonist wearing stylish jacket and dark aviators",
        startSec: 1.0,
        endSec: 5.5,
        originalDialogue: "Tum log hard work karo, hum system se smart work karte hain.",
        emotionalExpression: "smug",
        headMotionPrompt: "Minimal steady movement, slow chin lift, calm confident smirk",
      },
    ],
    defaultScript: "Rule #1: Stop doing 2015 manual tasks. Automate the entire workflow in one tap.",
    tags: ["sigma", "chai", "hustle", "bangalore_tech", "delhi_gurgaon", "brainrot"],
  },
  {
    templateId: "in_brainrot_04_desi_parent_reaction",
    title: 'Desi Mom / Dad "Paisa Barbaad" vs Brand Solution',
    category: "Desi Comedy",
    format: "before_after_comparison",
    previewVideoUrl:
      "https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-man-working-on-a-computer-keyboard-41586-large.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80",
    durationSec: 8,
    aspectRatio: "9:16",
    viralHook: "POV: Explaining your online business expenses to Indian parents",
    humorMechanism: "Classic Indian parental dialogue contrast turned into a high-ROI brand flex",
    culturalContext: "Relatable Indian family banter regarding value for money and smart investments",
    metrics: { plays: 4200000, likes: 540000, comments: 18900 },
    beats: [
      {
        timestampSec: 0,
        durationSec: 3.5,
        label: "Parental Skepticism",
        visualAction: 'Expressive reaction simulating typical Indian parent asking "Kitna kharcha kiya?"',
        originalAudioCue: "Classic comedy sitar pluck and funny whistle",
        suggestedBrandAction: "Highlight expensive outdated agency or tool cost",
      },
      {
        timestampSec: 3.5,
        durationSec: 4.5,
        label: "The ROI Proof Flex",
        visualAction: "Showing phone screen with 10x ROI and 90% cost savings, parent smiling approvingly",
        originalAudioCue: "Triumphant celebratory Punjabi Dhol beat drop",
        suggestedBrandAction: "Reveal Brand affordable pricing and massive results",
      },
    ],
    textSlots: [
      {
        slotId: "top_header",
        defaultText: "EXPLAINING EXPENSES TO PARENTS:",
        placement: "top",
        fontSize: "large",
        fontStyle: "bold_impact",
        backgroundColor: "#000000CC",
        textColor: "#FFFFFF",
      },
      {
        slotId: "bottom_punchline",
        defaultText: 'When they see 10x output at 1/10th cost: "Shabaash beta" 👏',
        placement: "bottom",
        fontSize: "medium",
        fontStyle: "classic_meme",
        backgroundColor: "#15803DEE",
        textColor: "#FFFFFF",
      },
    ],
    audioPlan: {
      trackType: "bgm",
      originalSoundName: "Desi Comedy Dhol Beat",
      suggestedTrackStyle: "Playful acoustic guitar into energetic festive dhol",
      bpm: 115,
      sfxCues: [
        { timestampSec: 0.1, sfxName: "record_scratch", volumeMultiplier: 0.6 },
        { timestampSec: 3.5, sfxName: "applause", volumeMultiplier: 0.9 },
      ],
    },
    lipSyncSlots: [
      {
        speakerId: "speaker_parent",
        speakerDescription: "Animated speaker with expressive eyebrow and hand movements",
        startSec: 0.5,
        endSec: 3.4,
        originalDialogue: "Itna paisa barbaar karne ki kya zaroorat thi?",
        emotionalExpression: "confused",
        headMotionPrompt: "Side-to-side head bobble, narrowed eyes, raised eyebrow",
      },
      {
        speakerId: "speaker_protagonist",
        speakerDescription: "Happy founder presenting laptop",
        startSec: 3.6,
        endSec: 7.2,
        originalDialogue: "Papa dekho, 10x speed aur 90% savings! Ab to shaabash de do!",
        emotionalExpression: "excited",
        headMotionPrompt: "Bright smile, open hands, nod of pride",
      },
    ],
    defaultScript:
      "Why spend thousands on bloated agencies when you can generate viral content with AI in seconds?",
    tags: ["family", "desi_comedy", "parent_meme", "relatable", "viral_india"],
  },
];
